apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      name: flask-pod
      labels: 
        app: flask
    spec:
      containers:
        - name: flask
          image: apptaskmanager:latest
          imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: flask-srv
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30005